/*
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * This code is generated by a tool and is provided "as is", without warranty of any kind,
 * express or implied, including but not limited to the warranties of merchantability,
 * fitness for a particular purpose and non-infringement.
 * In no event shall the authors or copyright holders be liable for any claim, damages or
 * other liability, whether in an action of contract, tort or otherwise, arising from,
 * out of or in connection with the software or the use or other dealings in the software.
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * */

namespace MySql_Windows_Forms_Project5
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.formsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmcustomer_tToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmorder_line_tToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmorder_tToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.frmproduct_tToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.menuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.formsToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(284, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // formsToolStripMenuItem
            // 
            this.formsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.frmcustomer_tToolStripMenuItem,
            this.frmorder_line_tToolStripMenuItem,
            this.frmorder_tToolStripMenuItem,
            this.frmproduct_tToolStripMenuItem});
            this.formsToolStripMenuItem.Name = "formsToolStripMenuItem";
            this.formsToolStripMenuItem.Size = new System.Drawing.Size(52, 20);
            this.formsToolStripMenuItem.Text = "Forms";
            // 
            // frmcustomer_tToolStripMenuItem
            // 
            this.frmcustomer_tToolStripMenuItem.Name = "frmcustomer_tToolStripMenuItem";
            this.frmcustomer_tToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.frmcustomer_tToolStripMenuItem.Text = "customer_t";
            this.frmcustomer_tToolStripMenuItem.Click += new System.EventHandler(this.frmcustomer_tToolStripMenuItem_Click);
            // 
            // frmorder_line_tToolStripMenuItem
            // 
            this.frmorder_line_tToolStripMenuItem.Name = "frmorder_line_tToolStripMenuItem";
            this.frmorder_line_tToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.frmorder_line_tToolStripMenuItem.Text = "order_line_t";
            this.frmorder_line_tToolStripMenuItem.Click += new System.EventHandler(this.frmorder_line_tToolStripMenuItem_Click);
            // 
            // frmorder_tToolStripMenuItem
            // 
            this.frmorder_tToolStripMenuItem.Name = "frmorder_tToolStripMenuItem";
            this.frmorder_tToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.frmorder_tToolStripMenuItem.Text = "order_t";
            this.frmorder_tToolStripMenuItem.Click += new System.EventHandler(this.frmorder_tToolStripMenuItem_Click);
            // 
            // frmproduct_tToolStripMenuItem
            // 
            this.frmproduct_tToolStripMenuItem.Name = "frmproduct_tToolStripMenuItem";
            this.frmproduct_tToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.frmproduct_tToolStripMenuItem.Text = "product_t";
            this.frmproduct_tToolStripMenuItem.Click += new System.EventHandler(this.frmproduct_tToolStripMenuItem_Click);
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(284, 261);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "frmMain";
            this.Text = "Main Form";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem formsToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmcustomer_tToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmorder_line_tToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmorder_tToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmproduct_tToolStripMenuItem;

    }
}
