/*
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * This code is generated by a tool and is provided "as is", without warranty of any kind,
 * express or implied, including but not limited to the warranties of merchantability,
 * fitness for a particular purpose and non-infringement.
 * In no event shall the authors or copyright holders be liable for any claim, damages or
 * other liability, whether in an action of contract, tort or otherwise, arising from,
 * out of or in connection with the software or the use or other dealings in the software.
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MySql_Windows_Forms_Project5
{
    public partial class frmMain : Form
    {
        public frmMain()
        {
            InitializeComponent();
        }


    private void frmcustomer_tToolStripMenuItem_Click(object sender, EventArgs e)
    {
      frmcustomer_t f = new frmcustomer_t();
      f.Show();
    }

    private void frmorder_line_tToolStripMenuItem_Click(object sender, EventArgs e)
    {
      frmorder_line_t f = new frmorder_line_t();
      f.Show();
    }

    private void frmorder_tToolStripMenuItem_Click(object sender, EventArgs e)
    {
      frmorder_t f = new frmorder_t();
      f.Show();
    }

    private void frmproduct_tToolStripMenuItem_Click(object sender, EventArgs e)
    {
      frmproduct_t f = new frmproduct_t();
      f.Show();
    }

    }
}
