/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Objects;

namespace MySql_Windows_Forms_Project5
{
	public partial class frmproduct_t : Form
	{
		private Model1Entities ctx;
		
		public frmproduct_t()
		{
			InitializeComponent();
		}
		
		private void frmproduct_t_Load(object sender, EventArgs e)
		{
			ctx = new Model1Entities();
			ObjectResult<product_t> _entities = ctx.product_t.Execute(MergeOption.AppendOnly);
			product_tBindingSource.DataSource = _entities;
			bindingNavigatorAddNewItem.Enabled = false;
			bindingNavigatorCountItem.Enabled = false;
			bindingNavigatorDeleteItem.Enabled = false;
			bindingNavigatorMoveFirstItem.Enabled = false;
			bindingNavigatorMovePreviousItem.Enabled = false;
			bindingNavigatorPositionItem.Enabled = false;
			bindingNavigatorMoveNextItem.Enabled = false;
			bindingNavigatorMoveLastItem.Enabled = false;
			toolStripButton1.Enabled = true;
			dataGridView1.AutoGenerateColumns = false;
			string strConn2 = "port=3306;server=localhost;user id=root;password=root;database=pinevalley;";
			MySql.Data.MySqlClient.MySqlDataAdapter ad2 = null;
			System.Windows.Forms.DataGridViewTextBoxColumn colproduct_id = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colproduct_id.DataPropertyName = "product_id";
			colproduct_id.HeaderText = "product_id";
			colproduct_id.Name = "colproduct_id";
			dataGridView1.Columns.Add(colproduct_id);
			System.Windows.Forms.DataGridViewTextBoxColumn colproduct_description = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colproduct_description.DataPropertyName = "product_description";
			colproduct_description.HeaderText = "product_description";
			colproduct_description.Name = "colproduct_description";
			dataGridView1.Columns.Add(colproduct_description);
			System.Windows.Forms.DataGridViewTextBoxColumn colproduct_finish = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colproduct_finish.DataPropertyName = "product_finish";
			colproduct_finish.HeaderText = "product_finish";
			colproduct_finish.Name = "colproduct_finish";
			dataGridView1.Columns.Add(colproduct_finish);
			System.Windows.Forms.DataGridViewTextBoxColumn colstandard_price = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colstandard_price.DataPropertyName = "standard_price";
			colstandard_price.HeaderText = "standard_price";
			colstandard_price.Name = "colstandard_price";
			dataGridView1.Columns.Add(colstandard_price);
			System.Windows.Forms.DataGridViewTextBoxColumn colproduct_line_id = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colproduct_line_id.DataPropertyName = "product_line_id";
			colproduct_line_id.HeaderText = "product_line_id";
			colproduct_line_id.Name = "colproduct_line_id";
			dataGridView1.Columns.Add(colproduct_line_id);
			dataGridView1.DataSource = _entities;
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			product_tBindingSource.EndEdit();
			ctx.SaveChanges();
			
		}
		
		private void frmproduct_t_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void dataGridView1_CellValidating(object sender, DataGridViewCellValidatingEventArgs e)
		{
			string s;
			DataGridViewRow row = dataGridView1.Rows[e.RowIndex];
			object value = e.FormattedValue;
			e.Cancel = false;
			row.ErrorText = "";
			if (row.IsNewRow) return;
			if (e.ColumnIndex == 0)
			{
				int v;
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field product_id is required";
					return;
				}
				s = value.ToString();
				if( !int.TryParse( s, out v ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field product_id must be int.";
					return;
				}
			}
			if (e.ColumnIndex == 1)
			{
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field product_description is required";
					return;
				}
			}
			if (e.ColumnIndex == 2)
			{
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field product_finish is required";
					return;
				}
			}
			if (e.ColumnIndex == 3)
			{
				double v;
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field standard_price is required";
					return;
				}
				s = value.ToString();
				if( !double.TryParse( s, out v ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field standard_price must be double.";
					return;
				}
			}
			if (e.ColumnIndex == 4)
			{
				int v;
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field product_line_id is required";
					return;
				}
				s = value.ToString();
				if( !int.TryParse( s, out v ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field product_line_id must be int.";
					return;
				}
			}
		}
		
		private void dataGridView1_DataError(object sender, DataGridViewDataErrorEventArgs e)
		{
			dataGridView1.Rows[e.RowIndex].ErrorText = e.Exception.Message;
			e.Cancel = true;
		}
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			product_tBindingSource.AddNew();
		}
	}
}
