//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MySql_Windows_Forms_Project5", "order_fk", "customer_t", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MySql_Windows_Forms_Project5.customer_t), "order_t", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MySql_Windows_Forms_Project5.order_t), true)]
[assembly: EdmRelationshipAttribute("MySql_Windows_Forms_Project5", "order_line_fk1", "order_t", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MySql_Windows_Forms_Project5.order_t), "order_line_t", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MySql_Windows_Forms_Project5.order_line_t), true)]
[assembly: EdmRelationshipAttribute("MySql_Windows_Forms_Project5", "order_line_fk2", "product_t", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MySql_Windows_Forms_Project5.product_t), "order_line_t", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MySql_Windows_Forms_Project5.order_line_t), true)]

#endregion

namespace MySql_Windows_Forms_Project5
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Entities object using the connection string found in the 'Model1Entities' section of the application configuration file.
        /// </summary>
        public Model1Entities() : base("name=Model1Entities", "Model1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Entities object.
        /// </summary>
        public Model1Entities(string connectionString) : base(connectionString, "Model1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Entities object.
        /// </summary>
        public Model1Entities(EntityConnection connection) : base(connection, "Model1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<customer_t> customer_t
        {
            get
            {
                if ((_customer_t == null))
                {
                    _customer_t = base.CreateObjectSet<customer_t>("customer_t");
                }
                return _customer_t;
            }
        }
        private ObjectSet<customer_t> _customer_t;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<order_line_t> order_line_t
        {
            get
            {
                if ((_order_line_t == null))
                {
                    _order_line_t = base.CreateObjectSet<order_line_t>("order_line_t");
                }
                return _order_line_t;
            }
        }
        private ObjectSet<order_line_t> _order_line_t;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<order_t> order_t
        {
            get
            {
                if ((_order_t == null))
                {
                    _order_t = base.CreateObjectSet<order_t>("order_t");
                }
                return _order_t;
            }
        }
        private ObjectSet<order_t> _order_t;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<product_t> product_t
        {
            get
            {
                if ((_product_t == null))
                {
                    _product_t = base.CreateObjectSet<product_t>("product_t");
                }
                return _product_t;
            }
        }
        private ObjectSet<product_t> _product_t;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the customer_t EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocustomer_t(customer_t customer_t)
        {
            base.AddObject("customer_t", customer_t);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the order_line_t EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToorder_line_t(order_line_t order_line_t)
        {
            base.AddObject("order_line_t", order_line_t);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the order_t EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToorder_t(order_t order_t)
        {
            base.AddObject("order_t", order_t);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the product_t EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproduct_t(product_t product_t)
        {
            base.AddObject("product_t", product_t);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MySql_Windows_Forms_Project5", Name="customer_t")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class customer_t : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new customer_t object.
        /// </summary>
        /// <param name="customer_id">Initial value of the customer_id property.</param>
        /// <param name="customer_name">Initial value of the customer_name property.</param>
        public static customer_t Createcustomer_t(global::System.Int32 customer_id, global::System.String customer_name)
        {
            customer_t customer_t = new customer_t();
            customer_t.customer_id = customer_id;
            customer_t.customer_name = customer_name;
            return customer_t;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 customer_id
        {
            get
            {
                return _customer_id;
            }
            set
            {
                if (_customer_id != value)
                {
                    Oncustomer_idChanging(value);
                    ReportPropertyChanging("customer_id");
                    _customer_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("customer_id");
                    Oncustomer_idChanged();
                }
            }
        }
        private global::System.Int32 _customer_id;
        partial void Oncustomer_idChanging(global::System.Int32 value);
        partial void Oncustomer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String customer_name
        {
            get
            {
                return _customer_name;
            }
            set
            {
                Oncustomer_nameChanging(value);
                ReportPropertyChanging("customer_name");
                _customer_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("customer_name");
                Oncustomer_nameChanged();
            }
        }
        private global::System.String _customer_name;
        partial void Oncustomer_nameChanging(global::System.String value);
        partial void Oncustomer_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String customer_address
        {
            get
            {
                return _customer_address;
            }
            set
            {
                Oncustomer_addressChanging(value);
                ReportPropertyChanging("customer_address");
                _customer_address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("customer_address");
                Oncustomer_addressChanged();
            }
        }
        private global::System.String _customer_address;
        partial void Oncustomer_addressChanging(global::System.String value);
        partial void Oncustomer_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String postal_code
        {
            get
            {
                return _postal_code;
            }
            set
            {
                Onpostal_codeChanging(value);
                ReportPropertyChanging("postal_code");
                _postal_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("postal_code");
                Onpostal_codeChanged();
            }
        }
        private global::System.String _postal_code;
        partial void Onpostal_codeChanging(global::System.String value);
        partial void Onpostal_codeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MySql_Windows_Forms_Project5", "order_fk", "order_t")]
        public EntityCollection<order_t> order_t
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<order_t>("MySql_Windows_Forms_Project5.order_fk", "order_t");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<order_t>("MySql_Windows_Forms_Project5.order_fk", "order_t", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MySql_Windows_Forms_Project5", Name="order_line_t")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order_line_t : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new order_line_t object.
        /// </summary>
        /// <param name="order_id">Initial value of the order_id property.</param>
        /// <param name="product_id">Initial value of the product_id property.</param>
        public static order_line_t Createorder_line_t(global::System.Int32 order_id, global::System.Int32 product_id)
        {
            order_line_t order_line_t = new order_line_t();
            order_line_t.order_id = order_id;
            order_line_t.product_id = product_id;
            return order_line_t;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 order_id
        {
            get
            {
                return _order_id;
            }
            set
            {
                if (_order_id != value)
                {
                    Onorder_idChanging(value);
                    ReportPropertyChanging("order_id");
                    _order_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("order_id");
                    Onorder_idChanged();
                }
            }
        }
        private global::System.Int32 _order_id;
        partial void Onorder_idChanging(global::System.Int32 value);
        partial void Onorder_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                if (_product_id != value)
                {
                    Onproduct_idChanging(value);
                    ReportPropertyChanging("product_id");
                    _product_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("product_id");
                    Onproduct_idChanged();
                }
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ordered_quantity
        {
            get
            {
                return _ordered_quantity;
            }
            set
            {
                Onordered_quantityChanging(value);
                ReportPropertyChanging("ordered_quantity");
                _ordered_quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ordered_quantity");
                Onordered_quantityChanged();
            }
        }
        private Nullable<global::System.Int32> _ordered_quantity;
        partial void Onordered_quantityChanging(Nullable<global::System.Int32> value);
        partial void Onordered_quantityChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MySql_Windows_Forms_Project5", "order_line_fk1", "order_t")]
        public order_t order_t
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<order_t>("MySql_Windows_Forms_Project5.order_line_fk1", "order_t").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<order_t>("MySql_Windows_Forms_Project5.order_line_fk1", "order_t").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<order_t> order_tReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<order_t>("MySql_Windows_Forms_Project5.order_line_fk1", "order_t");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<order_t>("MySql_Windows_Forms_Project5.order_line_fk1", "order_t", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MySql_Windows_Forms_Project5", "order_line_fk2", "product_t")]
        public product_t product_t
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product_t>("MySql_Windows_Forms_Project5.order_line_fk2", "product_t").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product_t>("MySql_Windows_Forms_Project5.order_line_fk2", "product_t").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<product_t> product_tReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product_t>("MySql_Windows_Forms_Project5.order_line_fk2", "product_t");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<product_t>("MySql_Windows_Forms_Project5.order_line_fk2", "product_t", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MySql_Windows_Forms_Project5", Name="order_t")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order_t : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new order_t object.
        /// </summary>
        /// <param name="order_id">Initial value of the order_id property.</param>
        public static order_t Createorder_t(global::System.Int32 order_id)
        {
            order_t order_t = new order_t();
            order_t.order_id = order_id;
            return order_t;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 order_id
        {
            get
            {
                return _order_id;
            }
            set
            {
                if (_order_id != value)
                {
                    Onorder_idChanging(value);
                    ReportPropertyChanging("order_id");
                    _order_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("order_id");
                    Onorder_idChanged();
                }
            }
        }
        private global::System.Int32 _order_id;
        partial void Onorder_idChanging(global::System.Int32 value);
        partial void Onorder_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> order_date
        {
            get
            {
                return _order_date;
            }
            set
            {
                Onorder_dateChanging(value);
                ReportPropertyChanging("order_date");
                _order_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_date");
                Onorder_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _order_date;
        partial void Onorder_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onorder_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> customer_id
        {
            get
            {
                return _customer_id;
            }
            set
            {
                Oncustomer_idChanging(value);
                ReportPropertyChanging("customer_id");
                _customer_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("customer_id");
                Oncustomer_idChanged();
            }
        }
        private Nullable<global::System.Int32> _customer_id;
        partial void Oncustomer_idChanging(Nullable<global::System.Int32> value);
        partial void Oncustomer_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MySql_Windows_Forms_Project5", "order_fk", "customer_t")]
        public customer_t customer_t
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<customer_t>("MySql_Windows_Forms_Project5.order_fk", "customer_t").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<customer_t>("MySql_Windows_Forms_Project5.order_fk", "customer_t").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<customer_t> customer_tReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<customer_t>("MySql_Windows_Forms_Project5.order_fk", "customer_t");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<customer_t>("MySql_Windows_Forms_Project5.order_fk", "customer_t", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MySql_Windows_Forms_Project5", "order_line_fk1", "order_line_t")]
        public EntityCollection<order_line_t> order_line_t
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<order_line_t>("MySql_Windows_Forms_Project5.order_line_fk1", "order_line_t");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<order_line_t>("MySql_Windows_Forms_Project5.order_line_fk1", "order_line_t", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MySql_Windows_Forms_Project5", Name="product_t")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class product_t : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new product_t object.
        /// </summary>
        /// <param name="product_id">Initial value of the product_id property.</param>
        public static product_t Createproduct_t(global::System.Int32 product_id)
        {
            product_t product_t = new product_t();
            product_t.product_id = product_id;
            return product_t;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                if (_product_id != value)
                {
                    Onproduct_idChanging(value);
                    ReportPropertyChanging("product_id");
                    _product_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("product_id");
                    Onproduct_idChanged();
                }
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_description
        {
            get
            {
                return _product_description;
            }
            set
            {
                Onproduct_descriptionChanging(value);
                ReportPropertyChanging("product_description");
                _product_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_description");
                Onproduct_descriptionChanged();
            }
        }
        private global::System.String _product_description;
        partial void Onproduct_descriptionChanging(global::System.String value);
        partial void Onproduct_descriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_finish
        {
            get
            {
                return _product_finish;
            }
            set
            {
                Onproduct_finishChanging(value);
                ReportPropertyChanging("product_finish");
                _product_finish = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_finish");
                Onproduct_finishChanged();
            }
        }
        private global::System.String _product_finish;
        partial void Onproduct_finishChanging(global::System.String value);
        partial void Onproduct_finishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> standard_price
        {
            get
            {
                return _standard_price;
            }
            set
            {
                Onstandard_priceChanging(value);
                ReportPropertyChanging("standard_price");
                _standard_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("standard_price");
                Onstandard_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _standard_price;
        partial void Onstandard_priceChanging(Nullable<global::System.Decimal> value);
        partial void Onstandard_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_line_id
        {
            get
            {
                return _product_line_id;
            }
            set
            {
                Onproduct_line_idChanging(value);
                ReportPropertyChanging("product_line_id");
                _product_line_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_line_id");
                Onproduct_line_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_line_id;
        partial void Onproduct_line_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_line_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MySql_Windows_Forms_Project5", "order_line_fk2", "order_line_t")]
        public EntityCollection<order_line_t> order_line_t
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<order_line_t>("MySql_Windows_Forms_Project5.order_line_fk2", "order_line_t");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<order_line_t>("MySql_Windows_Forms_Project5.order_line_fk2", "order_line_t", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
